version: '3.7'
services:
  traefik:
    restart: always
    image: traefik
    command: --docker --accessLog.filePath="/access.log"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt/live/vkolesov.com/fullchain.pem:/cert.crt
      - /etc/letsencrypt/live/vkolesov.com/privkey.pem:/key.key
      - ./.data/traefik/traefik.toml:/traefik.toml
      - ./access.log:/access.log
  nginx:
    restart: always
    image: "nginx:stable"
    labels:
      - "traefik.frontend.rule=Host:${MAIN_HOST};PathPrefix:/static"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./blog/static:/var/www/${MAIN_HOST}/static"
  blog:
    restart: always
    container_name: app
    build:
      context: ./blog
    tty: true
    volumes:
      - "./blog:/app"
      - "./.data/blog_db:/data"
    env_file:
      - .env
    labels:
      - "traefik.frontend.rule=Host:${MAIN_HOST}"
